name: JATS

on:
  push:
  pull_request:

jobs:
  jats:
    name: JATS
    runs-on: ubuntu-latest
    env:
      VALIDATOR_URL: "https://jats-validator.hubmed.org/dtd/"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run pandoc
        uses: 'docker://pandoc/core:latest'
        with:
          args: >-
            --to=jats_articleauthoring+element_citations
            --output=paper.jats.xml
            --standalone
            paper.md

      - name: Validate writer output
        run: |
          filename=paper.jats.xml
          printf "Validating file %s\n" "$filename"
          json="$(curl --form "xml=@${filename}" --silent "$VALIDATOR_URL")"
          err_count="$(printf '%s' "$json" | jq '.errors | length')"
          if [ "$err_count" -eq 0 ]; then
              printf "File was validated successfully.\n"
              exit 0
          else
              printf "Validator report:\n%s" "$json"
              exit 1
          fi

      - name: Upload JATS output
        uses: actions/upload-artifact@v1
        with:
          name: paper.jats.xml
          path: paper.jats.xml
