name: JATS

on:
  push:
  pull_request:

jobs:
  jats:
    name: JATS
    runs-on: ubuntu-latest
    env:
      VALIDATOR_URL: "https://jats-validator.hubmed.org/dtd/"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run pandoc
        uses: 'docker://pandoc/core:latest'
        with:
          args: >-
            --to=jats_articleauthoring+element_citations
            --output=paper.jats.xml
            paper.md

      - name: Upload JATS output
        uses: actions/upload-artifact@v1
        with:
          name: paper.jats.xml
          path: paper.jats.xml
